version: ""

formatter: markdown table

name: aws-terraform-cloud-q

content: |-
  [![Qumulo Logo](https://qumulo.com/wp-content/uploads/2021/06/CloudQ-Logo_OnLight.png)](http://qumulo.com)

  # aws-terraform-cloud-q [![Latest Release](https://img.shields.io/github/release/qumulo/aws-terraform-cloud-q.svg)](https://github.com/qumulo/aws-terraform-cloud-q/releases)

  Comprehensive Terraform to deploy a Qumulo cluster with 4 to 20 instances per the AWS Well Architected Framework.
  Supports usable capacities from 1TB to 6PB with all Qumulo Core features.

  ## AWS Requirements

  This Terraform deploys Qumulo AMIs with [Qumulo Core Cloud Software](https://qumulo.com/product/cloud-products/) version `>= 5.1.0.1`

  A subscription to a Qumulo offer in [AWS Marketplace](https://aws.amazon.com/marketplace/search/results?x=0&y=0&searchTerms=qumulo) is required.
  For private offers via the AWS Marketplace contact [Qumulo Sales](http://discover.qumulo.com/cloud-calc-contact.html).

  ## Planning the Deployment

  Reference Architecture:
  ![Ref Arch](./docs/qumulo-cloud-q-architecture_diagram.png)

  For help planning the deployment see the table of documents below.

  |Documentation|Description|
  |-------------|-----------|
  |[DNS options in AWS: IP failover & client distribution](https://qumulo.com/resources/qumulo-dns-options-in-aws/) | Details on the DNS options in AWS.|
  |[Terraform: Supported AWS Regions](./docs/tf-supported-regions.pdf) | Details on supported AWS Regions for Cloud Q with Terraform.|
  |[Terraform: Deploying in a VPC with no outbound internet access](./docs/tf-deploying-without-inet.pdf) | Details on deploying with Terraform into a VPC that has no outbound internet access.|
  |[Terraform: Deploying using an AWS Custom IAM role](./docs/tf-deploying-with-custom-iam-role.pdf) | Details on deploying with Terraform using a custom IAM role.|
  |[Terraform: AWS resources & EBS Service Quota planning](./docs/tf-resources-ebs-quota-planning.pdf) | Details on service-quota planning for Amazon EBS, including EC2 instance types and EBS volume types.|
  |[Terraform: Qumulo sizing & performance on AWS](./docs/tf-qumulo-sizing-performance.pdf) | Details on Qumulo cluster performance and scalability on AWS.|
  
  ## Deploying with Terraform

  ### Deployment Considerations
  
  * You may deploy this as a module pinned to this repo or clone this repo and deploy in your local Terraform environment as a module or directly.
  * Pinning Example: git::https://github.com/Qumulo/aws-terraform-cloud-q.git?ref=v3.3
  * Cloning Example: git clone https://github.com/Qumulo/aws-terraform-cloud-q.git --branch v3.3 --single-branch
  <br />

  **IMPORTANT:** When pinning or cloning this repository specify the tagged release version because there may be breaking changes between releases. If you want the latest, reference 'main' realizing there may be breaking changes for your deployment.

  ### Terraform Naming Guidance
  There are a multitude of Terraform workflows from those that just use a default local workspace to those using Terraform Cloud with remote state.  The very first variable in the example files provided is **deployment_name**.  Some users may choose to make this the workspace name.  Other users may want the same deployment name in multiple workspaces. Regardless, a **deployment_unique_name** is generated that consists of the deployment name appended with an 11 digit random alphanumeric.  All resources are tagged with the **deployment_unique_name**.  The **deployment_unique_name** will never change on subsequent Terraform applies.  All subsequent changes to **deployment_name** are ingored.  No matter your naming convention or how you choose to use Terraform, you will have your chosen name and uniquely named resources so no conflicts occur between NLBs, resource groups, cross-regional CloudWatch views, etc.
  <br />

  **IMPORTANT:** If you are spinning up multiple clusters, define unique values for the **q_cluster_name** variable.  If using the optional Route53 PHZ, also define a unique value for **q_fqdn_name** for each cluster.

  ### Inputs Comparison
  Select between the minimalist **examples/standard.tf** or the fully featured **examples/advanced.tf**.  The file **terraform.tfvars** is a copy of the input values from **examples/advanced.tf** in this repository. These files all have extensive comments providing guidance on each variable.  The standard version makes many decisions for you to simplify the input process and deploy a Qumulo cluster with the software version of the Qumulo AMI.  The advanced version provides the flexibility that most production environments will require, as seen in the table below.

  |  | examples/standard.tf | examples/advanced.tf |
  |--|:---------------:|:---------------:|
  | Deploy in a Local Zone || ✅ |
  | Deploy on Outposts || ✅ |
  | Deploy with a Custom AMI-ID || ✅ |
  | Customize Qumulo Admin Password | ✅ | ✅ |
  | Customize EC2 Instance Type | ✅ | ✅ |
  | Customize EC2 Instance Count | ✅ | ✅ | 
  | Customize Termination Protection | ✅ | ✅ |
  | Customize EBS gp3 IOPS/Throughput || ✅ |  
  | Customize Qumulo Cluster Name || ✅ |
  | Customize Qumulo Software Version || ✅ |
  | Customize Qumulo Sidecar Deployment || ✅ |
  | Customize Qumulo # of Floating IPs || ✅ |
  | Optional: Add SNS Topics for EC2 & EBS Recovery || ✅ |
  | Optional: Add R53 PHZ DNS for Floating IPs || ✅ |
  | Optional: Add CIDRS to Qumulo Security Group || ✅ |
  | Optional: Add SG IDs to Qumulo Cluster || ✅ |
  | Optional: Add Qumulo Public Management || ✅ |
  | Optional: Add Qumulo Public Replication Port || ✅ |
  | Optional: Enable CloudWatch Audit Log Messages || ✅ |
  | Optional: Apply KMS CMK for EBS Encryption || ✅ |
  | Optional: Set IAM Permissions Boundary || ✅ |
  | Optional: Set Environment Type || ✅ |

  ---

  ### Standard Deployment Example

  ```hcl
  {{ include "examples/standard.tf" }}
  ```

  ### Advanced Deployment Example

  ```hcl
  {{ include "examples/advanced.tf" }}
  ```

  ## Post-Deployment
  If you're using Qumulo Core version 4.3.0 or newer, you can populate data on your Qumulo cluster by copying data from an Amazon S3 bucket using [Qumulo Shift for Amazon S3](https://qumulo.com/wp-content/uploads/2020/06/ShiftForAWS_DataSheet.pdf).

  For more information on Qumulo SHIFT, custom CloudWatch Dashboards, adding nodes, the provisioning instance, and destroying the cluster see the documents in the table below.

  |Documentation|Description|
  |-------------|-----------|
  |[Qumulo SHIFT: Copy from Amazon S3](https://github.com/Qumulo/docs/blob/gh-pages/shift-from-s3.md)| Copy data from S3 with the Qumulo GUI/CLI/API. |
  |[Qumulo SHIFT: Copy to Amazon S3](https://github.com/Qumulo/docs/blob/gh-pages/shift-to-s3.md)| Copy data to S3 with the Qumulo GUI/CLI/API. |
  |[Terraform: Using the Custom CloudWatch Dashboard](./docs/tf-cloudwatch-dashboard.pdf)| Details on viewing the CloudWatch dashboard and resource groups that are created for the Qumulo cluster.|
  |[Terraform: Supported Updates](./docs/tf-update-deployment.pdf)| Details on Terraform update options and examples, including adding instances (nodes) to the cluster and upgrading the Qumulo Sidecar.|
  |[Terraform: Provisioning Instance Functions](./docs/tf-provisioning-instance-functions.pdf)| Details on the functions of the provisioner instance.|
  |[Terraform: Destroying the Cluster](./docs/tf-destroy-deployment.pdf)| Details on backing up data, termination protection, and on cleaning up an AWS KMS customer managed key policy. |

  ---

  ## Terraform Documentation

  This repo is self documenting via Terraform-Docs.

  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  ## Help

  Please post all feedback via the AWS GitHub repository feedback link.

  __Note:__ This project is provided as a public service to the AWS/Terraform
  community and is not directly supported by Qumulo's paid enterprise support. It is
  intended to be used by expert users only.

  ## Copyright

  Copyright © 2022 [Qumulo, Inc.](https://qumulo.com)

  ## License

  [![License](https://img.shields.io/badge/license-MIT-green)](https://opensource.org/licenses/MIT)

  See [LICENSE](LICENSE) for full details

  ## Trademarks

  All other trademarks referenced herein are the property of their respective owners.

  ### Contributors

  - [Dack Busch](https://github.com/dackbusch) - Co-creator
  - [Gokul Kupparaj](https://github.com/gokulku) - Co-creator
  - [Wesley Kirkland](https://github.com/wesleykirklandsg) - Added Terraform automatic documentation

sections:
  show:
    - requirements
    - inputs
    - outputs

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace
